# Generated by Django 4.2.7 on 2026-09-25 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0001_initial'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerecord',
            name='matter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake', to='matters.matter'),
        ),
    ]
