# Generated by Django 4.2.7 on 2026-09-25 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Access request'), ('DELETION', 'Deletion request')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under review'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined')], default='REQUESTED', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(fields=('user', 'purpose'), name='unique_user_consent_purpose'),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
