# Generated by Django 4.2.7 on 2026-09-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('signaling_provider', models.CharField(default='awaiting-owner-integration', max_length=80)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='consultations.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
