# Generated by Django 4.2.7 on 2026-09-25 06:22

import apps.documents.models
import apps.documents.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=apps.documents.storage.PrivateDocumentStorage(), upload_to=apps.documents.models.private_document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending security review'), ('AVAILABLE', 'Available'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=30)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='matters.matter')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
