# Generated by Django 4.2.7 on 2026-09-25 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
        ('matters', '0001_initial'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting advocate review'), ('CLEAR', 'No conflict recorded'), ('FLAGGED', 'Requires review')], default='PENDING', max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_checks', to='advocates.advocateprofile')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_checks', to='matters.matter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
