# Generated by Django 4.2.7 on 2026-09-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_conflictcheck'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conflictcheck',
            constraint=models.UniqueConstraint(fields=('matter', 'advocate'), name='unique_matter_advocate_conflict'),
        ),
    ]
